language: cpp

compiler:
  - clang

cache: apt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential python libqt4-dev qt4-qmake libgdal-dev libhdf5-serial-dev libproj-dev

install:
  - cd corelib
  - qmake
  - make

script: cd test && python testload.py
